# Generated by Django 3.1.1 on 2020-12-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region_motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size_motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beratMotor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemilik_motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nameMotor', models.CharField(max_length=100)),
                ('brand_motor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garageproject.brand_motor')),
                ('size_motor', models.ManyToManyField(to='garageproject.Size_motor')),
            ],
        ),
        migrations.AddField(
            model_name='brand_motor',
            name='region_motor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garageproject.region_motor'),
        ),
    ]
